name: docker-buildx

on:
  push:
    branches: 
    - master
    paths-ignore:
        - 'README.md'
        - '.github/workflows/update-dockerhub-description-readme.yml'
  
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,linux/s390x

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Available_platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: ${{ steps.buildx.outputs.platforms }}
          tags: scyto/infinitude:latest
     
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
