name: docker-buildx

on:
  push:
    branches: master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Available_platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: ${{ steps.buildx.outputs.platforms }}
          tags: scyto/infinitude:github-autobuild-docker
     
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
